# Generated by Django 4.1.3 on 2022-11-21 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='datacriacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 15, 53, 25, 545292, tzinfo=datetime.timezone.utc)),
        ),
    ]
