# Generated by Django 4.1.3 on 2022-11-21 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar_alter_contato_datacriacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='datacriacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 20, 6, 10, 456697, tzinfo=datetime.timezone.utc)),
        ),
    ]
